name: Run R package tests in renv

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check-r-package:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'renv' # use lockfile version
    - uses: r-lib/actions/setup-renv@v2
    - name: Run tests in renv
      run: |
        R -e "install.packages('devtools')"
        R -e "devtools::test('seirMeasles')"
