name: Run R package tests in renv

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check-r-package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        r_package: [chainsR, seirMeasles]

    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with:
        r-version: 'renv' # use lockfile version
    - name: Install system dependencies
      run: |
        sudo apt-get install -y libgdal-dev
        sudo apt-get install -y gdal-bin
        sudo apt-get install -y libgeos-dev
        sudo apt-get install -y libproj-dev
        sudo apt-get install -y libsqlite3-dev
        sudo apt-get install -y libudunits2-dev
    - uses: r-lib/actions/setup-renv@v2
    - name: Run tests in renv
      run: R -e "devtools::test('${{ matrix.r_package }}')"
